# Generated by Django 3.2.7 on 2022-04-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellenous', '0003_rename_reviewed_recipe_review_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='categories/default.jpg', upload_to='categories'),
        ),
    ]
