# Generated by Django 3.2.7 on 2022-04-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220419_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeimage',
            options={'ordering': ['recipe'], 'verbose_name': 'Recipe Image', 'verbose_name_plural': 'Recipe Images'},
        ),
        migrations.AddField(
            model_name='ingredientitem',
            name='image',
            field=models.ImageField(default='default_ingredient.jpg', upload_to='ingredient_items'),
        ),
        migrations.AddField(
            model_name='utensilitem',
            name='image',
            field=models.ImageField(default='default_utensil.jpg', upload_to='utensil_items'),
        ),
    ]
