# Generated by Django 3.2.7 on 2022-04-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220419_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utensilitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
