# Generated by Django 3.2.7 on 2022-04-20 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_alter_utensilitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Maximum 120 characters', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Maximum 120 characters', max_length=120),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('c', 'cup'), ('pt', 'pint'), ('qt', 'quart'), ('gal', 'gallon'), ('ml', 'milliliter'), ('l', 'liter'), ('dl', 'deciliter'), ('fl oz', 'fluid ounce'), ('lb', 'pound'), ('oz', 'ounce'), ('mg', 'milligram'), ('g', 'gram'), ('kg', 'kilogram'), ('mm', 'millimeter'), ('cm', 'centimeter'), ('m', 'meter'), ('in', 'inch')], help_text='Maximum 50 characters', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(to='recipes.Category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cost',
            field=models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High')], max_length=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('e', 'Easy'), ('m', 'Medium'), ('h', 'Hard')], max_length=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=120, unique=True, verbose_name='Recipe|Title'),
        ),
        migrations.AlterField(
            model_name='utensil',
            name='name',
            field=models.CharField(help_text='Maximum 120 characters', max_length=120),
        ),
        migrations.AlterField(
            model_name='utensilitem',
            name='utensil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.utensil'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=1)),
                ('content', models.TextField(blank=True, max_length=1024, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('user', models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
