# Generated by Django 3.2.7 on 2022-04-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellenous', '0001_initial'),
        ('recipes', '0005_auto_20220420_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(to='miscellenous.Category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
