# Generated by Django 3.2.7 on 2022-04-20 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscellenous', '0001_initial'),
        ('recipes', '0006_auto_20220420_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='ingredientitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='utensilitem',
            name='image',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(default='default_ingredient.jpg', upload_to='ingredient_items'),
        ),
        migrations.AddField(
            model_name='ingredientitem',
            name='unit',
            field=models.CharField(default='', help_text='Maximum 50 characters', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utensil',
            name='image',
            field=models.ImageField(default='default_utensil.jpg', upload_to='utensil_items'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miscellenous.category'),
        ),
    ]
