# Generated by Django 3.2.7 on 2022-04-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20220421_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientitem',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientitem',
            name='unit',
            field=models.CharField(blank=True, help_text='Maximum 50 characters', max_length=10, null=True),
        ),
    ]
