# Generated by Django 3.2.7 on 2022-04-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20220421_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientitem',
            name='quantity',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utensilitem',
            name='quantity',
            field=models.CharField(max_length=10),
        ),
    ]
