# Generated by Django 3.2.7 on 2022-04-20 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20220421_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientitem',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient'),
        ),
    ]
