# Generated by Django 3.2.7 on 2022-04-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_ingredientitem_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cost',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(max_length=1),
        ),
    ]
