# Generated by Django 3.2.7 on 2022-04-21 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20220421_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rest_time',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
