# Generated by Django 3.2.7 on 2022-04-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20220421_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cost',
            field=models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High')], max_length=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('v', 'Very Easy'), ('e', 'Easy'), ('m', 'Medium'), ('h', 'Hard')], max_length=1),
        ),
    ]
