# Generated by Django 3.2.7 on 2022-04-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20220421_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Maximum 120 characters', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='utensil',
            name='name',
            field=models.CharField(help_text='Maximum 120 characters', max_length=120, unique=True),
        ),
    ]
