# Generated by Django 3.2.7 on 2022-04-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20220422_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='num_of_dishes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
