# Generated by Django 3.2.7 on 2022-04-24 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscellenous', '0005_rename_user_review_owner'),
        ('recipes', '0015_recipe_num_of_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='miscellenous.category'),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to='recipe_images'),
        ),
    ]
