# Generated by Django 3.2.7 on 2022-04-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20220424_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(default='ingredients/default_ingredient.jpg', upload_to='ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cost',
            field=models.CharField(choices=[('c', 'Cheap'), ('m', 'Medium'), ('e', 'Expensive')], max_length=1),
        ),
        migrations.AlterField(
            model_name='utensil',
            name='image',
            field=models.ImageField(default='utensils/default_utensil.jpg', upload_to='utensils'),
        ),
    ]
