# Generated by Django 3.2.7 on 2022-04-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20220424_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='youtube_link',
            field=models.URLField(default=''),
        ),
    ]
