# Generated by Django 3.2.7 on 2022-04-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_rename_youtube_link_recipe_youtube_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
